sequence:
  - script: ../../DriveHealth_Final_All.ps1
    display: "XRDCWWTAPPCAC21B  (APP)"
    env:
      ORBIT_DH_ENVS: "PreProd"
      ORBIT_DH_SITE: "NFD"
      ORBIT_DH_SERVER: "XRDCWWTAPPCAC21B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "XRDCWWTDBSCAC21B  (DB)"
    env:
      ORBIT_DH_ENVS: "PreProd"
      ORBIT_DH_SITE: "NFD"
      ORBIT_DH_SERVER: "XRDCWWTDBSCAC21B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "XRDCWWTINTCAC21B  (INTERFACE)"
    env:
      ORBIT_DH_ENVS: "PreProd"
      ORBIT_DH_SITE: "NFD"
      ORBIT_DH_SERVER: "XRDCWWTINTCAC21B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "XRDCWWTRPTCAC21B  (REPORT)"
    env:
      ORBIT_DH_ENVS: "PreProd"
      ORBIT_DH_SITE: "NFD"
      ORBIT_DH_SERVER: "XRDCWWTRPTCAC21B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "XRDCWWTWEBCAC21B  (WEB)"
    env:
      ORBIT_DH_ENVS: "PreProd"
      ORBIT_DH_SITE: "NFD"
      ORBIT_DH_SERVER: "XRDCWWTWEBCAC21B"
