sequence:
  - script: ../../DriveHealth_Final_All.ps1
    display: "FWDCWWPAPPCAC01B  (APP)"
    env:
      ORBIT_DH_ENVS: "Prod"
      ORBIT_DH_SITE: "SAN"
      ORBIT_DH_SERVER: "FWDCWWPAPPCAC01B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "FWDCWWPDBSCAC01B  (DB)"
    env:
      ORBIT_DH_ENVS: "Prod"
      ORBIT_DH_SITE: "SAN"
      ORBIT_DH_SERVER: "FWDCWWPDBSCAC01B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "FWDCWWPINTCAC01B  (INTERFACE)"
    env:
      ORBIT_DH_ENVS: "Prod"
      ORBIT_DH_SITE: "SAN"
      ORBIT_DH_SERVER: "FWDCWWPINTCAC01B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "FWDCWWPRPTCAC01B  (REPORT)"
    env:
      ORBIT_DH_ENVS: "Prod"
      ORBIT_DH_SITE: "SAN"
      ORBIT_DH_SERVER: "FWDCWWPRPTCAC01B"
  - script: ../../DriveHealth_Final_All.ps1
    display: "FWDCWWPWEBCAC01B  (WEB)"
    env:
      ORBIT_DH_ENVS: "Prod"
      ORBIT_DH_SITE: "SAN"
      ORBIT_DH_SERVER: "FWDCWWPWEBCAC01B"
